[package]
name = "game_of_life"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
simple = { path = "../simple" }

[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-arg=-sUSE_SDL=2"
]
